CFLAGS = -Wall -Wextra -Werror -Wno-unused-parameter

q1:bin
	gcc $(CFLAGS) -o bin/q1 question_1.c
q2:bin
	gcc $(CFLAGS) -o bin/q2 question_2.c
q3:bin
	gcc $(CFLAGS) -o bin/q3 question_3.c
q4:bin
	gcc $(CFLAGS) -o bin/q4 question_4.c
q5:bin
	gcc $(CFLAGS) -o bin/q5 question_5.c
q6:bin
	gcc $(CFLAGS) -o bin/q6 question_6.c
q7:bin
	gcc $(CFLAGS) -o bin/q7 question_7.c
q8:bin
	gcc $(CFLAGS) -o bin/q8 question_8.c
bin:
	mkdir -p bin
